# Site
repository: glay415/glay415.github.io
# favicon: images/favicon.ico

# Personal info
name: 이준서
title: 서버 백엔드 엔지니어
email: magpieprinc@gmail.com
#website: https://jojoldu.tistory.com

# Social links
# twitter_username: jojoldu
github_username:  glay415
# dribbble_username: jekyll
#facebook_username: jojoldu
# flickr_username: jekyll
linkedin_username: 준서-이-75241a228
# pinterest_username: jekyll
#youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요, **대덕소프트웨어 마이스터 고등학교 재학** 중인 이준서입니다. **Java**와 **Kotlin**을 활용해 **Spring Boot**를 다루며, 
  클라우드 기술을 활용한 <mark>서버 아키텍처 설계와 개발 방법론</mark>에 관심이 있습니다. <br/>
  학교에서 Entry라는 동아리의 부장직을 맡아 학교의 **입학전형 시스템을 개발 & 운영**해보았고, **기숙사 관리 시스템**과 **레주메관리 시스템**
  등 여러 프로젝트들을 통해 실무적인 역량을 키웠습니다. 그 과정에서 새로운 기술과 패러다임을 적용해보기도 하고 여러 시행착오와 
  협업을 거쳐 **저와 팀의 성장**을 이끌어낸 바 있습니다. <br/> <br/>
  저는 <mark>지속적인 학습과 혁신</mark>을 추구하며, 새로운 패러다임과 기술에 관심을 가지고 있습니다. 
  끊임없이 발전하는 IT 산업에서 빠르게 변화에 적응하고, 업계의 선두를 달리는 전문가로 성장하고자 합니다.<br/>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여러 주제로 발표와 기고, 출판을 해왔습니다.
   - [인프콘 2022 - 인프런 아키텍처의 과거, 현재 그리고 미래](https://www.youtube.com/watch?v=D_QH50UkX_4)
   - [MongoDB Day Seoul 2022 - 초기 스타트업과 MongoDB Search](https://www.ddaily.co.kr/news/article/?no=249222)
   - [우아콘 2020 - 수십억건에서 Querydsl 사용하기](https://www.youtube.com/watch?v=zMAX7g6rO_Y)
   - [스프링 부트와 AWS로 혼자 구현하는 웹 서비스](https://jojoldu.tistory.com/463)
   - [EO 인터뷰](https://www.youtube.com/watch?v=V9AGvwPmnZU&t=2s)
   - [2019 우아한 스프링 배치](https://www.youtube.com/watch?v=_nkJkWVH-mo&t=14s)
   - [인프런 - IntelliJ IDEA 가이드](https://www.inflearn.com/course/intellij-guide)
   - [2018 KCD - IntelliJ IDEA만으로 개발하기](https://www.youtube.com/watch?v=wBXSUdT1jX0)
   - [2018 JetBrains Day - Upsource를 이용한 코드리뷰](https://www.youtube.com/watch?v=06bJt6CnRAU&feature=youtu.be)
   - [마소 394호 - AWS EC2와 TravisCI를 활용한 무중단 배포 서비스](http://it.chosun.com/site/data/html_dir/2018/10/29/2018102900482.html)
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
